### ISSUE TITLE
Change filter icon in the mobile version

### ISSUE THREAD

**Issue by AgaFra** [Problematy/goodmap-frontend#40]
In mobile version, the icon for expand filters is this same to expand pages:
![image](https://github.com/Problematy/goodmap-frontend/assets/79878967/a95cc7de-e92a-4f38-9c8d-571e2b3826d7)
Let's change hamburger to an icon more related to filter - slider icon:
![image](https://github.com/Problematy/goodmap-frontend/assets/79878967/2c5d03e8-3155-4473-a09e-8d6e36c03beb)

**Comment by raven-wing** [comment]
It's been dealt with in [this pull request](https://github.com/Problematy/goodmap/pull/76)
