### ISSUE TITLE
Add 'report an issue' to place description

### ISSUE THREAD

**Issue by raven-wing** [Problematy/goodmap-frontend#5]
After clicking 'report an issue' there should be popup with textbox where user should write `description` of an issue. There should also be prefilled textboxes with `place id` and `coordinates`.

It should be posted then to `/api/issue`

**Comment by raven-wing** [comment]
@AgaFra could you attach mockup how could it work?

**Comment by raven-wing** [comment]
@Davcode1234 will take this issue

**Comment by AgaFra** [comment]
![image](https://user-images.githubusercontent.com/79878967/211205408-a571d2bd-e27d-47ca-986d-134fe48b0903.png)

By clicking on "Report an issue" it should direct to the form describe in the next image.
![image2](https://user-images.githubusercontent.com/79878967/211205410-6c8cd793-f97b-417b-9311-6d4547afadd9.png)
